<a href="https://colab.research.google.com/github/Ryoya0627/Pro2kakusin/blob/main/work2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*work2*

題名

ナンプレ

説明

ナンプレをnumpyで作りました。苦労した点は、最初に埋まっている数字のところの座標を一つ一つしてしたため、リストのindexの量が多くなったことです。

In [43]:
import numpy as np
def Numberplace1():
  a=np.array([[9,6,2,8,7,3,4,1,5],
            [1,8,5,9,2,4,7,6,3],
            [3,7,4,1,6,5,9,2,8],
            [4,9,6,2,3,8,1,5,7],
            [2,1,8,5,4,7,3,9,6],
            [7,5,3,6,9,1,2,8,4],
            [5,3,1,4,8,9,6,7,2],
            [6,4,9,7,5,2,8,3,1],
            [8,2,7,3,1,6,5,4,9]])
  b=np.zeros((9,9))
  c=[(0,1),(0,5),(1,5),(1,6),(1,8),(2,1),(2,2),(2,3),(2,7),(3,0),(3,1),(3,4),(3,5),(3,7),(3,8),(4,0),(4,2),(4,4),(4,7),(4,8),(5,0),(5,3),(5,6),(5,8),(6,0),(6,2),(6,3),(6,4),(6,5),(6,6),(7,2),(7,7),(7,8),(8,3),(8,4),(8,5),(8,6),(8,8)]
  for i in c:
    b[i]=a[i]
  print(b)
  print()
  l=[1,2,3,4,5,6,7,8,9]

  count=0
  while 0 in b:
    print('座標は?:')
    d=int(input('行:'))-1
    e=int(input('列:'))-1
    k=int(input('数字は?:'))
    if a[d,e]==k:
      b[d,e]=k
    else:
      count+=1
      print('ミス'+str(count)+'回目です。')
      print()
    if count==3:
      print('失敗です!!')
      print(a)
      break
    else:
      print()
      print(b)
      print()
      number=0
      for x in range(9):
        for y in range(9):
          if b[x,y]==k:
            number+=1
      if number==9:
        l.remove(k)
      print('残りは',l)
      print()

def Numberplace2():
  a=np.array([[5,1,9,6,8,7,4,3,2],
            [7,2,4,9,1,3,6,5,8],
            [3,8,6,2,5,4,9,1,7],
            [1,7,8,3,4,5,2,9,6],
            [6,5,2,8,9,1,7,4,3],
            [9,4,3,7,2,6,5,8,1],
            [2,3,1,4,7,9,8,6,5],
            [4,6,7,5,3,8,1,2,9],
            [8,9,5,1,6,2,3,7,4]])
  b=np.zeros((9,9))
  c=[(0,1),(0,6),(0,7),(1,0),(2,3),(2,4),(2,5),(2,6),(3,0),(3,1),(3,4),(3,6),(3,8),(4,4),(4,8),(5,2),(5,5),(5,7),(6,2),(6,3),(6,4),(6,7),(7,3),(7,5),(7,6),(7,7),(8,1),(8,4),(8,6),(8,8)]
  for i in c:
    b[i]=a[i]
  print(b)
  print()
  l=[1,2,3,4,5,6,7,8,9]

  count=0
  while 0 in b:
    print('座標は?:')
    d=int(input('行:'))-1
    e=int(input('列:'))-1
    k=int(input('数字は?:'))
    if a[d,e]==k:
      b[d,e]=k
    else:
      count+=1
      print('ミス'+str(count)+'回目です。')
      print()
    if count==3:
      print('失敗です!!')
      print(a)
      break
    else:
      print()
      print(b)
      print()
      number=0
      for x in range(9):
        for y in range(9):
          if b[x,y]==k:
            number+=1
      if number==9:
        l.remove(k)
      print('残りは',l)
      print()

def Numberplace3():
  a=np.array([[1,3,2,6,8,5,4,7,9],
            [5,9,8,7,3,4,1,6,2],
            [7,6,4,2,1,9,5,3,8],
            [4,2,7,5,6,8,9,1,3],
            [9,1,5,3,4,2,6,8,7],
            [6,8,3,1,9,7,2,5,4],
            [2,5,6,4,7,3,8,9,1],
            [8,7,1,9,2,6,3,4,5],
            [3,4,9,8,5,1,7,2,6]])
  b=np.zeros((9,9))
  c=[(0,5),(0,6),(1,0),(1,4),(1,7),(2,2),(2,4),(2,5),(2,8),(3,3),(3,5),(3,6),(3,8),(4,8),(5,0),(5,1),(5,5),(6,0),(6,1),(6,4),(6,8),(7,2),(7,3),(7,7),(7,8),(8,0),(8,2),(8,6),(8,7),(8,8)]
  for i in c:
    b[i]=a[i]
  print(b)
  print()
  l=[1,2,3,4,5,6,7,8,9]

  count=0
  while 0 in b:
    print('座標は?:')
    d=int(input('行:'))-1
    e=int(input('列:'))-1
    k=int(input('数字は?:'))
    if a[d,e]==k:
      b[d,e]=k
    else:
      count+=1
      print('ミス'+str(count)+'回目です。')
      print()
    if count==3:
      print('失敗です!!')
      print(a)
      break
    else:
      print()
      print(b)
      print()
      number=0
      for x in range(9):
        for y in range(9):
          if b[x,y]==k:
            number+=1
      if number==9:
        l.remove(k)
      print('残りは',l)
      print()

In [44]:
m=np.random.randint(1,3)
if m==1:
  print(Numberplace1())
elif m==2:
  print(Numberplace2())
else:
  print(Numberplace3())

[[0. 1. 0. 0. 0. 0. 4. 3. 0.]
 [7. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 5. 4. 9. 0. 0.]
 [1. 7. 0. 0. 4. 0. 2. 0. 6.]
 [0. 0. 0. 0. 9. 0. 0. 0. 3.]
 [0. 0. 3. 0. 0. 6. 0. 8. 0.]
 [0. 0. 1. 4. 7. 0. 0. 6. 0.]
 [0. 0. 0. 5. 0. 8. 1. 2. 0.]
 [0. 9. 0. 0. 6. 0. 3. 0. 4.]]

座標は?:
行:2
列:3
数字は?:3
ミス1回目です。


[[0. 1. 0. 0. 0. 0. 4. 3. 0.]
 [7. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 5. 4. 9. 0. 0.]
 [1. 7. 0. 0. 4. 0. 2. 0. 6.]
 [0. 0. 0. 0. 9. 0. 0. 0. 3.]
 [0. 0. 3. 0. 0. 6. 0. 8. 0.]
 [0. 0. 1. 4. 7. 0. 0. 6. 0.]
 [0. 0. 0. 5. 0. 8. 1. 2. 0.]
 [0. 9. 0. 0. 6. 0. 3. 0. 4.]]

残りは [1, 2, 3, 4, 5, 6, 7, 8, 9]

座標は?:
行:3
列:6
数字は?:3
ミス2回目です。


[[0. 1. 0. 0. 0. 0. 4. 3. 0.]
 [7. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 5. 4. 9. 0. 0.]
 [1. 7. 0. 0. 4. 0. 2. 0. 6.]
 [0. 0. 0. 0. 9. 0. 0. 0. 3.]
 [0. 0. 3. 0. 0. 6. 0. 8. 0.]
 [0. 0. 1. 4. 7. 0. 0. 6. 0.]
 [0. 0. 0. 5. 0. 8. 1. 2. 0.]
 [0. 9. 0. 0. 6. 0. 3. 0. 4.]]

残りは [1, 2, 3, 4, 5, 6, 7, 8, 9]

座標は?:
行:5
列:5
数字は?:4
ミス3回目です。

失敗です!!
[[5 1 9 6 8 7 4 